import Layout from '@/componants/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/sd.png'
import AnimatedText from '@/componants/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/componants/Icons'
import HireMe from '@/componants/HireMe'
import lightbulb from "../../public/images/svgs/miscellaneous_icons_1.svg"



export default function Home() {
  return (
    <>
      <Head>
        <title>Shubham Devkamble's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen  dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className="flex items-center justify-between w-full lg:flex-col lg:text-center">
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt='shubhamd' className='w-full h-auto lg:hidden md:inline-block md:w-full'
                priority
                sizes='{max-width:768px} 100vw,
                {max-width: 1200px} 50vw,50vw'
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center '> 
          
              <AnimatedText text="Turning Vision Into Reality With Code And Design."
                className='!text-6xl !text-center  xl:!text-5xl lg:!text-center lg:!text-4xl  md:!text-5xl  sm:!sm-3xl' />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                 As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/shubhamd.pdf" target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark
                 hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                 md:p-2 md:px-4 md:text-base'
                  download={true}>
                  Resume <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                <Link href="mailto:shubhamdevkamble707@gmail.com" target={"_blank"}
                  className='ml-4 text-lg font-medium capitalize text-dark
                 underline dark:text-light hover:dark:bg-dark hover:dark:text-light md:text-base'>Contact</Link>
              </div>
            </div>
          </div>
          
        </Layout>
         
        <HireMe />
        
        <div className='absolute right-8 bottom-8 inline-block w-20 md:hidden'>
          <Image src={lightbulb} alt='shubhamd' className='w-full h-auto'/>
        </div>
      </main>
    </>
  )
}
